server:
  port: 8080

spring:
  application:
    name: medical-reserve
  datasource:
    url: jdbc:mysql://localhost:3306/medical_reserve?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.forth.medicalreserve.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: medical-reserve-secret-key
  expiration: 86400000  # 24 hours

logging:
  level:
    com.forth.medicalreserve: debug
  file:
    name: logs/medical-reserve.log

springfox:
  documentation:
    swagger-ui:
      enabled: true 